### ISSUE TITLE
Can't resolve 'near-api-js/lib/utils/errors' - @near-wallet-selector/ledger

### ISSUE THREAD

**Issue by thangnq666** [near/wallet-selector#423] opened 2022-08-25 15:27 UTC
**Describe the bug** Can't resolve 'near-api-js/lib/utils/errors' in '/Users/nthellious/Documents/project/near-lend/nearlend-fe/node_modules/@near-wallet-selector/ledger'

**To Reproduce** Here my current **tsconfig.json** { "compilerOptions": 

 { "target": "es2015", "module": "esnext", "lib": ["es2017", "dom"], "allowJs": true, "jsx": "react-native", "noEmit": true, "isolatedModules": true, "moduleResolution": "node", "allowSyntheticDefaultImports": true, "esModuleInterop": true, "skipLibCheck": true, "resolveJsonModule": true, "sourceMap": true, "declaration": false, "emitDecoratorMetadata": true, "experimentalDecorators": true, "importHelpers": true, "skipDefaultLibCheck": true, "baseUrl": "src" } 

, "include": <span class="error">["src"]</span>, "exclude": [ "node_modules", "tmp", "babel.config.js", "jest.config.js", ".babelrc.js", ".eslint.json", "tmp" ] }

and my **package.json** { "name": "frontend", "version": "0.1.0", "private": true, "dependencies": 

 { "@ant-design/icons": "^4.7.0", "@hookstate/core": "^3.0.13", "@jscutlery/semver": "^2.25.2", "@ledgerhq/hw-transport": "^6.27.1", "@ledgerhq/hw-transport-webhid": "^6.27.1", "@meteorwallet/sdk": "0.3.0", "@near-wallet-selector/core": "^6.0.0", "@near-wallet-selector/default-wallets": "^6.0.0", "@near-wallet-selector/ledger": "^6.0.0", "@near-wallet-selector/math-wallet": "^6.0.0", "@near-wallet-selector/meteor-wallet": "^6.0.0", "@near-wallet-selector/modal-ui": "^6.0.0", "@near-wallet-selector/my-near-wallet": "^6.0.0", "@near-wallet-selector/near-wallet": "^6.0.0", "@near-wallet-selector/nightly": "^6.0.0", "@near-wallet-selector/nightly-connect": "^6.0.0", "@near-wallet-selector/sender": "^6.0.0", "@near-wallet-selector/wallet-connect": "^6.0.0", "@nightlylabs/connect": "0.0.23", "@testing-library/jest-dom": "^5.14.1", "@testing-library/react": "^12.0.0", "@testing-library/user-event": "^13.2.1", "@types/jest": "^27.0.1", "@types/node": "^16.7.13", "@types/react": "^17.0.20", "@types/react-dom": "^17.0.9", "@types/react-router-dom": "^5.3.3", "@walletconnect/qrcode-modal": "2.0.0-alpha.20", "@walletconnect/sign-client": "^2.0.0-beta.102", "antd": "^4.18.2", "aos": "^3.0.0-beta.6", "axios": "^0.25.0", "big.js": "^6.2.1", "buffer": "^6.0.3", "dayjs": "^1.11.4", "decimal.js": "^10.3.1", "near-api-js": "^0.45.1", "react": "^17.0.2", "react-dom": "^17.0.2", "react-query": "^3.39.1", "react-router-dom": "^6.2.1", "react-scripts": "5.0.0", "rxjs": "^7.5.6", "sass": "^1.52.1", "styled-components": "^5.3.5", "web-vitals": "^2.1.0" } 

, "scripts": 

 { "start": "react-scripts start", "build": "react-scripts build", "build-deploy": "react-scripts build && firebase deploy", "test": "react-scripts test", "eject": "react-scripts eject" } 

, "eslintConfig": 

 { "extends": [ "react-app", "react-app/jest" ] } 

, "browserslist": 

 { "production": [ ">0.2%", "not dead", "not op_mini all" ], "development": [ "last 1 chrome version", "last 1 firefox version", "last 1 safari version" ] } 

, "devDependencies": 

 { "@ant-design/plots": "^1.0.7", "@types/aos": "^3.0.4", "@types/styled-components": "^5.1.25", "babel-plugin-module-resolver": "^4.1.0", "html-webpack-plugin": "^5.5.0", "ts-loader": "^9.2.6", "typescript": "^4.5.4" } 

, "resolutions": 

 { "styled-components": "^5" } 

 }

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/63598425/186706081-fd7edee0-8e74-4c43-af23-c37d22de9a40.png)</span>](https://user-images.githubusercontent.com/63598425/186706081-fd7edee0-8e74-4c43-af23-c37d22de9a40.png)

I don't really know what happen for this setting up it just show this error that cannot found in * _@near-wallet-selector/ledger_ *

**Comment by kujtimprenkuSQA** [comment] 2022-08-25 16:57
Hey, @thangnq666 thank you for raising this issue.

This error started showing up recently as far as we know it's happening in React apps that use Webpack 5.

This is caused by an import  we have in the `@near-wallet-selector/ledger` from `near-api-js`, we have worked on this issue here: https://github.com/near/wallet-selector/pull/419 we are planing on publishing a new minor release to fix this issue.

In the meantime **The request 'near-api-js/lib/utils/errors' failed to resolve only because it was resolved as fully specified** can be fixed by extending the webpack config and adding this code:

```ts
const webpack = require('webpack');
module.exports = function override(config) {
  // react-dnd
  config.module.rules.unshift({
    test: /\.m?js$/,
    resolve: {
      fullySpecified: false, // disable the behaviour
    },
  });
  return config;
}
```

**Comment by kujtimprenkuSQA** [comment] 2022-08-30 11:21
Hey, @thangnq666 we made a new release a few days ago `v6.0.1` which should include a fix for the issue you're having.
NPM: https://www.npmjs.com/org/near-wallet-selector
Release notes: https://github.com/near/wallet-selector/releases/tag/v6.0.1

**Closed** 2022-08-30 11:24 UTC
Labels: bug
