### ISSUE TITLE
Function to request wallet sign a message (a string, not a transaction).

### ISSUE THREAD

**Issue by phucloc8697** [near/wallet-selector#318] opened 2022-06-08 07:30 UTC
**Is your feature request related to a problem? Please describe.** My application has a feature that require user to sign a message (a string of some data we defined ourself) using their wallet, and our backend will verify later.

**Describe the solution you'd like** Add function named "signMessage" (for example) took a string as parameter and return signed string.

**Additional context** Refer to similar function in EVM

/**

*   @params sign - ethers.providers.JsonRpcSigner
*   @params message - string data need to be signed */ await signer.signMessage(ethers.utils.arrayify(message));

**Comment by lewis-sqa** [comment] 2022-06-08 07:56
Hi @phucloc8697,

Thanks for raising this enhancement. I'd like to dig a little deeper into the use case of this. What's the intention for signing exactly? Will the message ever be sent to the blockchain is maybe the idea to use this as a way to verify ownership of the message later on (as you mentioned by the backend)?

I should set the expectation that we're at the mercy of what the wallets we support can do. Off the top of my head, this should be possible with Ledger and Math Wallet but I'm almost certain Sender for example doesn't provide low-level signing like this. It only exposes signing (and sending) [Transactions](https://nomicon.io/RuntimeSpec/Transactions)

**Comment by phucloc8697** [comment] 2022-06-09 00:52
Hi @lewis-sqa ,

1. Yes, I would need it to verify ownership of the message. Nothing will be sent to the blockchain.

2. If so, could you throw an exception in case the wallet doesn't provide signing method? Beside  that, I would contact Sender and ask if they can provide this feature.

**Comment by lewis-sqa** [comment] 2022-06-09 07:35
@phucloc8697 thanks for providing some clarity on this 👍 

I've done some investigation with Sender as I realise it's since implemented the `Account` class/interface from `near-api-js` which happens to ultimately expose the `Signer` functionality so in theory it should be possible!

We've raised a ticket internally to address this enhancement. We'll keep you posted here on the progress 🙂

**Comment by phucloc8697** [comment] 2022-06-09 09:50
@lewis-sqa  Nice one! Thanks for your support

**Comment by lewis-sqa** [comment] 2022-06-15 15:44
@phucloc8697 So I believe a `Signer.signMessage` implementation tends to be backed ultimately by a `KeyPair`'s `sign` method. The issue is really the security concerns of `signMessage` as arbitrary messages lack the protection detailed in [EIP-712](https://eips.ethereum.org/EIPS/eip-712).

The block on this feature for us with Wallet Selector is the lack of spec from NEAR around how a dedicated verify ownership method will work. We're hoping to get some clarity on this in the next week

**Comment by mohamedalichelbi** [comment] 2022-07-16 17:34
> I can create key pair from BrowserLocalStorageKeyStore, and use this method generate a signed message.

Few considerations:
The key in your Dapp's localStorage will be a FunctionCall access key. It's the key generated upon user login, not the "main" key used to approve arbitrary TXs. But you should be able to use it for signatures. Just keep in mind that a NEAR account can always add or delete keys, so you'll also need to save the time at which the message was signed. When verifying the signature, you'll need to fetch the account's keys' list at the signature time.

**Comment by agileurbanite** [comment] 2022-08-15 17:39
Looks like this might be a blocker for AstroDAO so need to consider for prioritization.

**Comment by janewang** [comment] 2022-08-16 16:26
@agileurbanite This should go out in today's release. cc @MaximusHaximus

**Comment by kujtimprenkuSQA** [comment] 2022-08-17 11:00
@phucloc8697 , @agileurbanite  NEAR Wallet Selector v6.0.0 has been published on NPM.
https://www.npmjs.com/org/near-wallet-selector

This issue has been addressed in this PR: https://github.com/near/wallet-selector/pull/391 . To find out which wallets support this feature at the moment read the description of the mentioned PR.

**Comment by austinabell** [comment] 2022-08-17 17:13
I disagree that this interface should be a string. Will this not limit the functionality if you want to sign binary data in the future? Am I misunderstanding JS types that `string` can be used in some way from a `Buffer`/`UInt8Array`?

Related #405 (I am blind and didn't notice this issue when I created)

**Comment by janewang** [comment] 2022-08-17 17:43
cc @MaximusHaximus please see above.

@AmmarHumackicSQA let's track this in our board so we could discuss. The feature is requested by a few large project and we could improve the implementation if needed, thank you.

**Comment by AmmarHumackicSQA** [comment] 2022-10-27 16:56
Hey everyone, the NEP for `verifyOwner` is in the works and here you can check the draft of it: https://github.com/near/NEPs/pull/413

**Comment by gagdiez** [comment] 2022-11-08 11:16
Is there any progress on this? The community keeps asking for it on a monthly basis.

**Comment by toteto** [comment] 2022-11-08 17:13
> Is there any progress on this? The community keeps asking for it on a monthly basis.

☝️ Agree, this issue should take higher priority!

**Comment by AmmarHumackicSQA** [comment] 2022-11-08 17:23
> Hey everyone, the NEP for `verifyOwner` is in the works and here you can check the draft of it: [near/NEPs#413](https://github.com/near/NEPs/pull/413)

As stated here ☝️, this is a work in progress. I see you guys @gagdiez @toteto already posted some questions there. Thanks!

**Comment by gagdiez** [comment] 2022-11-15 23:41
@lewis-sqa @AmmarHumackicSQA @austinabell, we have greatly advanced the [NEP413](https://github.com/near/NEPs/pull/413), your feedback is appreciated. We are reaching consensus in the community, so maybe we could start readily implementing it in the wallet selector?

**Closed** 2022-11-18 16:17 UTC
Labels: enhancement
