### ISSUE TITLE
wallet-connect random disconnect

### ISSUE THREAD

**Issue by sumedhtare** [near/wallet-selector#715] opened 2023-02-28 13:25 UTC
wallet-connect randomly disconnects post successful transaction
note: this happens mostly after doing 2-3 function calls

1. connect to wallet using wallet-connect
2. make any function call and accept/approve the transaction

wallet-connect should stay connected after successful transaction even and should disconnect only when disconnect function is called

**Device (please complete the following information):**
 - OS: [Windows, iOS]
 - Browser [chrome, safari]

**Additional context**
you might need to repeat the function calls 2-3 times to replicate this error

**Comment by kujtimprenkuSQA** [comment] 2023-02-28 14:50
Hey, @sumedhtare thank you for raising this issue.

With which wallet are you connecting, just tested and it looks like it's working fine for us.

dApp: https://near.github.io/wallet-selector/
wallet example: https://react-wallet.walletconnect.com/

![Screenshot 2023-02-28 154752](https://user-images.githubusercontent.com/95851345/221889177-9d9766fa-b4a9-49f5-99fe-30313e08a46a.png)
m/

**Comment by sumedhtare** [comment] 2023-02-28 15:13
I tried connecting with opto wallet (android device) for Near

**Comment by kujtimprenkuSQA** [comment] 2023-02-28 15:30
Unfortunately, I can not replicate the issue you're having (tested on iOS phone with Opto wallet now):

![screencapture-near-github-io-wallet-selector-2023-02-28-16_26_34](https://user-images.githubusercontent.com/95851345/221899809-c3afe08b-dd5b-42aa-97b0-36cd6f4f78fb.png)

I will ask other team members who own an Android to test it out and get back to you.

**Comment by sumedhtare** [comment] 2023-02-28 15:30
sure thank you

**Comment by kujtimprenkuSQA** [comment] 2023-03-01 10:18
Hey, @sumedhtare the other team members have tested WalletConnect + Opto Wallet on an Android phone - android version 12.0 and it's working for them just fine.

Can you please try again?

Just to test it out can you try connecting with the wallet example: https://react-wallet.walletconnect.com/

If the issue is still showing up for you we will inform the Opto Wallet.

**Comment by AmmarHumackicSQA** [comment] 2023-03-07 11:47
> Hey, @sumedhtare the other team members have tested WalletConnect + Opto Wallet on an Android phone - android version 12.0 and it's working for them just fine.
> 
> Can you please try again?
> 
> Just to test it out can you try connecting with the wallet example: https://react-wallet.walletconnect.com/
> 
> If the issue is still showing up for you we will inform the Opto Wallet.

Hi @sumedhtare, have you tried the mentioned 👆? Do you have any additional questions regarding this or we can close the issue? Thanks!

**Comment by sumedhtare** [comment] 2023-03-09 04:22
@kujtimprenkuSQA it still disconnects for me and my other team members.
here's the link https://www.staderlabs.com/near/lt/near/?tab=Stake
connect your wallet using wallet-connect and try to stake/un-stake/withdraw multiple times.
The wallet disconnect after couple of successful transactions.

These are the installed packages
    "@near-wallet-selector/core": "7.8.2",
    "@near-wallet-selector/default-wallets": "^7.5.0",
    "@near-wallet-selector/here-wallet": "^7.5.0",
    "@near-wallet-selector/ledger": "6.0.0",
    "@near-wallet-selector/math-wallet": "5.0.2",
    "@near-wallet-selector/meteor-wallet": "^6.0.0",
    "@near-wallet-selector/modal-ui": "5.0.2",
    "@near-wallet-selector/my-near-wallet": "7.8.0",
    "@near-wallet-selector/near-wallet": "7.8.0",
    "@near-wallet-selector/nearfi": "^7.5.0",
    "@near-wallet-selector/nightly": "7.5.0",
    "@near-wallet-selector/nightly-connect": "5.0.2",
    "@near-wallet-selector/opto-wallet": "^7.5.0",
    "@near-wallet-selector/sender": "7.5.0",
    "@near-wallet-selector/wallet-connect": "7.8.0",

**Comment by kujtimprenkuSQA** [comment] 2023-03-09 09:31
If there are any errors in the console could you please attach a screenshot of the error here?

**Comment by sumedhtare** [comment] 2023-03-09 13:39
> > here's the link for testnet https://near-dapp-5ei7lrzan-staderlabs.vercel.app/lt/near/?tab=Stake
> 
> Can you set a `projectId` in the setupWalletConnect(params) function I can not initiate the connection without it.

here is the new link
https://near-dapp-hamidmd-staderlabs.vercel.app/lt/near/?tab=Stake

**Comment by kujtimprenkuSQA** [comment] 2023-03-10 09:51
@sumedhtare thank you for providing the link, for testnet.

Yesterday we have tried it on different android mobile phones but for some reason, we can not reproduce the issue you and your team are having, we are still connected.

Account ids used to stake and unstake in the above dApp (in different mobile phones):

http://explorer.testnet.near.org/accounts/kujtimprenku.testnet
https://explorer.testnet.near.org/accounts/7074cfabe9100482cc714ba9c9f2dc01c67c9998d3c22439dc64244f6fff8ef7
https://explorer.testnet.near.org/accounts/damir.testnet

Would it be possible to do a screen recording of the random disconnect, so that when the Opto Wallet team checks it out they might have any idea why this is happening?

The only time when we disconnect from the session is when the [signOut](https://github.com/near/wallet-selector/blob/main/packages/wallet-connect/src/lib/wallet-connect.ts#L431) method is called.

We will reach out to the Opto Wallet team and let them know.

**Comment by sumedhtare** [comment] 2023-03-13 13:22
Please find the link below for the requested video.
https://drive.google.com/drive/folders/100YECwSCI9dhE-8vsbdFodUAZyZFBRf1

**Comment by kujtimprenkuSQA** [comment] 2023-03-13 14:54
> Please find the link below for the requested video. https://drive.google.com/drive/folders/100YECwSCI9dhE-8vsbdFodUAZyZFBRf1

Thank you for providing the video, it is a really strange case.

If you set the `debug` to true in the `setupWalletSelector(params)` after you get `randomly` disconnected you will see something like this: (the `session_delete` is emitted by the opto wallet for some reason)

![logger](https://user-images.githubusercontent.com/95851345/224734639-669884eb-01a8-430c-a408-62469b8b2387.png)

I was able to reproduce the strange disconnect shown in the video with an old android phone:

**Android version** 8.1.0
**Phone model**: Samsung J7 max
**Samsung experience version**: 9.5

What we can do on our side is test if updating the WalletConnect-related dependencies will help it, if not It will be up to Opto Wallet team to check and hopefully find a fix.

**Comment by kujtimprenkuSQA** [comment] 2023-03-15 08:02
Hi, @sumedhtare I think I found out what the issue is for the "random" disconnect.

To reproduce this "random" disconnect with Opto Wallet try:

1. Send a transaction that requires a deposit (in your app "stake/unstake").
2. Once the confirm modal opens in Opto Wallet click the "Confirm" button.
3. Enter your password.
4. As soon as the password view closes click again the "Confirm" button and this will cause that sudden/random disconnect.

Can you try the above and see if the "disconnect" is happening only in the cases I described?

The reason why it was happening for me on Android was that the Android phone was kinda slow and sometimes I clicked the "Confirm" button twice (maybe by accident) and this emitted the "session_delete" from the Opto Wallet.

From my investigation so far I could not find any other reason why this "random" disconnect would happen.

**Comment by kujtimprenkuSQA** [comment] 2023-03-21 09:44
@sumedhtare the issue has been already fixed please install the latest version of Opto Wallet.

**Closed by kujtimprenkuSQA** 2023-03-21 09:44 UTC
Labels: bug
