### ISSUE TITLE
Failing to login in by meteor wallet  on mobile safari 

### ISSUE THREAD

**Issue by max-mainnet** [near/wallet-selector#451] opened 2022-09-12 11:04 UTC
**Describe the bug**

when I was to use [wallet selector example| %5Bnear.github.io/wallet-selector/%5D([https://near.github.io/wallet-selector/](https://near.github.io/wallet-selector/))] to try meteor wallet on mobile safari, failed to open meteor wallet official website to import accounts ( No accounts imported before ).

**To Reproduce** Steps to reproduce the behavior:

1.  Go to [wallet selector example| %5Bnear.github.io/wallet-selector/%5D([https://near.github.io/wallet-selector/](https://near.github.io/wallet-selector/))]on mobile safari browser(private mode)
2.  Click on meteor wallet
3.  Click on 'Get Start with Meteor Wallet'
4.  jump back to near example website, not behave like PC version to get start and import accounts.

**Expected behavior** When I click on Get Start With Meteor Wallet, should behave like PC version, then introduce me to import accounts on meteor wallet website.

**Screenshots**

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/50706666/189639192-34fe394c-9bb0-44a8-b3cb-6ff60e724730.jpg)</span>](https://user-images.githubusercontent.com/50706666/189639192-34fe394c-9bb0-44a8-b3cb-6ff60e724730.jpg)

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/50706666/189639204-9a000ec6-cd00-487f-8003-6a60d2b81639.jpg)</span>](https://user-images.githubusercontent.com/50706666/189639204-9a000ec6-cd00-487f-8003-6a60d2b81639.jpg)

**Device (please complete the following information):**

*   OS: IOS 15.2.1
*   Browser safari

**Comment by AmmarHumackicSQA** [comment] 2022-09-12 14:33
> seems like a bug on meteor wallet site, error to redirect back to app site.

Hi @max-mainnet , thanks for reporting. We have noticed it too, and we will reach out to the Meteor Wallet team.

**Comment by kujtimprenkuSQA** [comment] 2022-09-13 12:08
Hey, @lostpebble can you have a look at this issue?
Tried joining the Meteor Wallet on discord but there were too many steps to verify and post the issue link there.

**Comment by lostpebble** [comment] 2022-09-16 11:23
Hi @max-mainnet @kujtimprenkuSQA ,

Sorry, I've been at hacking Nearcon this past week- looking into this now. Seems strange that Safari links back to the original site instead of ours- could be because we are using a "relative" link (so that the website and extension link within their relative environments) and for some reason relative links seem to act differently on Safari when it comes to popups.

Thanks for notifying us about the issue @max-mainnet !

**Comment by lostpebble** [comment] 2022-09-19 08:07
Hi @max-mainnet - could you please give it another try and let me know?

I've changed the link from a relative one to a direct one- so hopefully Safari doesn't do anything strange with that.

**Comment by max-mainnet** [comment] 2022-09-21 10:05
> 

hi @lostpebble , as I can see, I don't think it works well in the same case on [wallet selector example ](https://near.github.io/wallet-selector/), could you test it on main mobile browsers ? Same error on chrome.

**Comment by lostpebble** [comment] 2022-09-21 10:22
Hi @max-mainnet - ah I see the issue now. The problem is that we're opening a new tab inside our main wallet site so users can go and create a new wallet- but it seems like the mobile browsers aren't focusing on that new tab and just going back to the old tab. Same thing happened to me on Firefox mobile now.

The idea was that once they've created the wallet and return to the dapp- they can read the error message there and "retry" the Meteor connection, which will now work because an account is created.

Will have to rethink this process a bit then. Maybe have to allow users to create the wallet inside that already opened tab and maintain some state of the action they're doing with the Wallet Selector so that once the account is created, we just continue where they left off directly.

**Comment by lostpebble** [comment] 2022-09-21 13:25
Hi again @max-mainnet 

I've just pushed the changes I mentioned above. You can now import your account directly and then finish the requested action with that account. Please let me know if that solves the issue for you.

**Comment by kujtimprenkuSQA** [comment] 2022-09-23 12:15
Hey, @lostpebble thank you for addressing this issue.

I have tested it in different mobile browsers and it works fine I think we can close the issue for now!

**Closed** 2022-09-23 12:16 UTC
Labels: bug
