### ISSUE TITLE
Vue example

### ISSUE THREAD

**Issue by Scofield-04-21-076** [near/wallet-selector#729] opened 2023-03-15 09:39 UTC
Are there any plans to add a Wallet Selector connection example on vue?

**Comment by kujtimprenkuSQA** [comment] 2023-03-15 11:37
Hi, @Scofield-04-21-076 thank you for raising this issue.

Currently, we don't have a Vue example under [examples](https://github.com/near/wallet-selector/tree/main/examples) mainly because there were problems with setting up a Vue example in NX with the version we're using now.

To setup wallet selector in a Vue project is very similar to what we have in our /examples.

You may find this project helpful: 
https://github.com/kujtimprenkuSQA/guest-book-vue

When building your Vue app created with Vite for production you might encounter an error thrown by `near-api-js` check out this issue to fix it (the issue is already fixed in the above project):
https://github.com/near/wallet-selector/issues/502#issuecomment-1284158448

**Comment by kujtimprenkuSQA** [comment] 2023-03-21 09:48
@Scofield-04-21-076 at the moment it's not possible for us to add a Vue project to our examples due to some issues with NX.

If you need help with Vue + wallet-selector please check the above project, and if you still have questions feel free to ask.

**Closed by kujtimprenkuSQA** 2023-03-21 09:48 UTC
Labels: enhancement
