### ISSUE TITLE
use wallet-connect to connect Fireblocks, the popup don't respond

### ISSUE THREAD

**Issue by tony-yyj** [near/wallet-selector#710] opened 2023-02-27 08:10 UTC
I use wallet-selector and choose wallet-connect to connect Fireblocks, allow connection in my phone, the dapp dialog don't closed, my phone status is connected, but dapp is not connected.

<img width="894" alt="image" src="https://user-images.githubusercontent.com/18418275/221508109-f29be66a-ea9c-448a-8640-bc26e987b473.png">

but if I use opto wallet, it's good work.

near-wallet-selector/core: 7.8.2
near-wallet-selector/wallet-connect: 7.8.2

**Comment by amirsaran3** [comment] 2023-02-27 12:46
Hey @tony-yyj, thanks for raising the issue.

I am not fully understanding your problem. Can you answer these questions so I can help you solve them:
1. What is the dApp where you are using wallet-selector?
2. How can I test this so I can reproduce this bug?
3. Are you testing on a phone or desktop?

**Comment by tony-yyj** [comment] 2023-02-28 02:48
> Hey @tony-yyj, thanks for raising the issue.
> 
> I am not fully understanding your problem. Can you answer these questions so I can help you solve them:
> 
> 1. What is the dApp where you are using wallet-selector?
> 2. How can I test this so I can reproduce this bug?
> 3. Are you testing on a phone or desktop?

I. https://dex.woo.org
2. I have test it in https://near.github.io/wallet-selector, it's also get no response, you can use it to test.
3. use Fireblocks mobile app to scan web dapp qrcode. 



<img width="1035" alt="image" src="https://user-images.githubusercontent.com/18418275/221739971-9d323708-92e6-40a8-a59c-c2169e9e8162.png">

**use Fireblocks mobile app to scan this qrcode, check ws session, ws session can get the account and accesskey, but the modal ui not close.**

I used opto mobile app to scan this qrcode, it's well done, ws get the account and accesskey, the modal ui is closed.

**Comment by amirsaran3** [comment] 2023-03-02 09:34
Hey @tony-yyj ,

We are not able to test this functionality because we can't create an account with Fireblocks. If you know how to can you check the console logs after you try to sign in using WalletConnect so we can know more about the issue. Or can we get access to a test Fireblocks account so we can test and debug this issue?

We are also speculating that you need to turn on some settings for NEAR in Fireblocks or NEAR is not supported by Fireblocks, so can you check that also.

Also are you testing on testnet or mainnet?

**Comment by AmmarHumackicSQA** [comment] 2023-03-07 11:50
Hi @tony-yyj , are you still experiencing the same issue or we can close this? Thanks!

**Comment by AmmarHumackicSQA** [comment] 2023-03-14 12:39
@tony-yyj I will close this issue as there is no response. Feel free to reopen it if needed. Thanks!

**Closed by AmmarHumackicSQA** 2023-03-14 12:39 UTC
Labels: bug
