### ISSUE TITLE
Developer Experience: Update Wallet Selector to have graceful defaults

### ISSUE THREAD

**Issue by agileurbanite** [near/wallet-selector#312] opened 2022-05-31 17:48 UTC
Today wallet selectors requires all DApps to re-deploy wallet selector when a new wallet is introduced.
Wallet selector also doesn't have any recommended defaults putting the onus of wallets to import on every DApp.

I'd like to recommend that wallet selector offers graceful defaults with the ability for DApp developers to override said defaults.

I'd also like to see wallet selector offer integration with an API to import wallets during runtime versus requiring a new bundle to be re-deployed when a new wallet is introduced in the ecosystem or within wallet selector.  This will be an endpoint that will be managed by the NEAR wallet services team.

## Ask

Can we create a design doc of a proposal on how to above asks can be addressed?

**Comment by agileurbanite** [comment] 2022-05-31 17:49
This was an interesting approach to how jupyterlab resolved this issue: https://github.com/jupyterlab/jupyterlab/issues/7468

**Comment by kujtimprenkuSQA** [comment] 2023-06-20 07:45
The issue is closed because Pagoda is not in the business of assigning which wallets are defaults. Wallet Selector will not have recommended defaults to support decentralization and give Wallets equal exposure.

Default wallets have been removed from the list: https://github.com/near/wallet-selector/pull/681

[@near-wallet-selector/default-wallets](https://www.npmjs.com/package/@near-wallet-selector/default-wallets) has been marked as deprecated.

**Closed by kujtimprenkuSQA** 2023-06-20 07:45 UTC
Labels: task
