### ISSUE TITLE
Module not found: Can't resolve 'encoding' in '...pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'

### ISSUE THREAD

**Issue by padiboi** [near/wallet-selector#748] opened 2023-03-31 15:08 UTC
**Describe the bug**

Description

Hey all, this is causing a build error when deploying to vercel -

```
warn  - ./node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '.../node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js
./node_modules/.pnpm/near-api-js@1.1.0/node_modules/near-api-js/lib/utils/setup-node-fetch.js
./node_modules/.pnpm/near-api-js@1.1.0/node_modules/near-api-js/lib/connect.js
./node_modules/.pnpm/near-api-js@1.1.0/node_modules/near-api-js/lib/index.js
./node_modules/.pnpm/@near-wallet-selector+core@7.9.0_near-api-js@1.1.0/node_modules/@near-wallet-selector/core/index.cjs
./contexts/WalletSelectorContext.tsx
```

### Steps to reproduce

Followed the wallet selector example to build a next js app

### Expected behavior

For 'encoding' to get resolved

### Actual behavior

Throwing an error related to near-api-js

### Your environment

NEAR JavaScript API version used: 1.1.0
Frontend framework (if applicable): Next.js 13
Relevant dependencies (if applicable): ./node_modules/.pnpm/node-fetch@2.6.9/node_modules/node-fetch/lib/index.js

**Comment by kujtimprenkuSQA** [comment] 2023-03-31 16:56
Hi, @padiboi thank you for raising this issue.

Can you please share a demo or tell us how to reproduce this error?

This is a copy of the `guest-book` example we have under wallet-selector/examples:
https://github.com/kujtimprenkuSQA/guest-book-nextjs

And I just deployed it on `vercel` everything seems to work fine in my case:
https://guest-book-nextjs.vercel.app/


Since the app above was created with `pnpm create next-app` I had to change the commands for installing and building accordingly in `vercel` to `pnpm install` and `pnpm build`

**Comment by AmmarHumackicSQA** [comment] 2023-04-07 11:57
Hi @padiboi and thanks for raising this issue! Let us know if you managed to solve it so we can close the issue.

**Comment by AmmarHumackicSQA** [comment] 2023-04-17 11:12
Hi @padiboi I will close this issue for now. Feel free to reopen it if needed. Thanks!

**Closed by AmmarHumackicSQA** 2023-04-17 11:12 UTC
Labels: bug
